export const ADD_ROW_REQUEST = "ADD_ROW_REQUEST";
export const ADD_ROW_SUCCESS = "ADD_ROW_SUCCESS";
export const ADD_ROW_FAILURE = "ADD_ROW_FAILURE";

export const ADD_CARD_REQUEST = "ADD_CARD_REQUEST";
export const ADD_CARD_SUCCESS = "ADD_CARD_SUCCESS";
export const ADD_CARD_FAILURE = "ADD_CARD_FAILURE";
